be more careful about downing services
swift-proxy likes to not shut down during grenade runs, and the
failure case just means all our tests take forever timing out on
trying to connect to it over glance.

put in a few more checks about whether the services are in the
right states.

Change-Id: Iedfd91cdded632f7f3a2b5f127c2901f8762adaa

diff --git a/check-sanity b/check-sanity
--- a/check-sanity
+++ b/check-sanity
@@ -25,6 +25,15 @@ source $GRENADE_DIR/grenaderc
 
 # We need the OS_ credentials
 source $TARGET_DEVSTACK_DIR/openrc
+source $TARGET_DEVSTACK_DIR/functions
+
+SERVICE_CHECK=`service_check`
+
+if [[ -n $SERVICE_CHECK ]]; then
+    echo "Failure to start some services"
+    echo $SERVICE_CHECK
+    exit 1
+fi
 
 # all the services should actually be running that we expect
 NOT_RUNNING=""
