add nova modular resource checks
This adds nova modular service checks, including the use of the
verify_noapi phase to ensure the server doesn't go away when
nova-compute is down (which is a substantial enhancement of our
existing validation).

There is slight regression in checking multiple servers, however that
did not seem to be a bug that we actually ran into.

add our own local copy of ping_check to grenade. The version in
devstack gets diverted down a neutron path even though we actually
want to use it in a public context. We need to change that code to
work on public networks regardless of backend. Until then, we'll keep
our own copy.

Change-Id: I985ca38ef670b03802f9ad67ce19cf94cfc802ae

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -16,6 +16,33 @@ source ${GRENADE_DIR}/inc/plugin
 XTRACE=$(set +o | grep xtrace)
 set +o xtrace
 
+# TODO: we'd really like to use the ping_check_functions that exist in
+# devstack, however they are all wrapped up in lib/neutron-legacy
+# gorp. Until that can be cleanly separated we need to keep our own
+# copy here.
+#
+# ping_check_public $ip $timeout [False] - ping an machine on a public
+# ip address. Should work with either neutron or nova-net. Also works
+# to ensure the guest is not up if you pass False as last parameter.
+function ping_check_public {
+    local ip=$1
+    local boot_timeout=$2
+    local expected=${3:-"True"}
+    local check_command=""
+    if [[ "$expected" = "True" ]]; then
+        check_command="while ! ping -c1 -w1 $ip; do sleep 1; done"
+    else
+        check_command="while ping -c1 -w1 $ip; do sleep 1; done"
+    fi
+    if ! timeout $boot_timeout sh -c "$check_command"; then
+        if [[ "$expected" = "True" ]]; then
+            die $LINENO "[Fail] Couldn't ping server"
+        else
+            die $LINENO "[Fail] Could ping server"
+        fi
+    fi
+}
+
 # save_data() dumps service datastores into SAVE_DIR for base or
 # target release.
 function save_data {
