Swift updates
* Move swift ahead of glance in upgrade order as glance depends on swiftclient
* Add some test files to Javelin project Swift storage
* Remove call to swift_init()
  * (re)Create cache dir
  * (re)Mount backing disk
* Restore the Swift port defaults

Change-Id: I14c1d50c13563cbc5fbb71de014e318951b6f62b

diff --git a/setup-javelin b/setup-javelin
--- a/setup-javelin
+++ b/setup-javelin
@@ -142,3 +142,11 @@ eval $BOOT_TXT
 if ! timeout $ACTIVE_TIMEOUT sh -c "while ! nova show $id | grep status | grep -q ACTIVE; do sleep 1; done"; then
     die $LINENO "server didn't become active!"
 fi
+
+# Put some stuff in Swift
+# -----------------------
+
+swift upload javelin /etc/hosts
+if ! swift list javelin | grep -q README; then
+    die $LINENO "Swift upload failed"
+fi
