Better identify error location
* turn on tracing in upgrade scripts
* add banners to upgrade scripts similar to DevStack exercises

diff --git a/upgrade-glance b/upgrade-glance
--- a/upgrade-glance
+++ b/upgrade-glance
@@ -2,6 +2,24 @@
 
 # ``upgrade-glance``
 
+echo "*********************************************************************"
+echo "Begin $0"
+echo "*********************************************************************"
+
+# Clean up any resources that may be in use
+cleanup() {
+    set +o errexit
+
+    echo "*********************************************************************"
+    echo "ERROR: Abort $0"
+    echo "*********************************************************************"
+
+    # Kill ourselves to signal any calling process
+    trap 2; kill -2 $$
+}
+
+trap cleanup SIGHUP SIGINT SIGTERM
+
 # Keep track of the grenade directory
 GRENADE_DIR=$(cd $(dirname "$0") && pwd)
 
@@ -16,7 +34,12 @@ GetDistro
 # Source params
 source $GRENADE_DIR/grenaderc
 
-# For debugging
+# This script exits on an error so that errors don't compound and you see
+# only the first error that occured.
+set -o errexit
+
+# Print the commands being run so that we can see the command that triggers
+# an error.  It is also useful for following allowing as the install occurs.
 set -o xtrace
 
 
@@ -87,3 +110,8 @@ glance-manage db_sync || die "DB sync error"
 # Start Glance
 screen_it g-reg "cd $GLANCE_DIR; bin/glance-registry --config-file=$GLANCE_CONF_DIR/glance-registry.conf"
 screen_it g-api "cd $GLANCE_DIR; bin/glance-api --config-file=$GLANCE_CONF_DIR/glance-api.conf"
+
+set +o xtrace
+echo "*********************************************************************"
+echo "SUCCESS: End $0"
+echo "*********************************************************************"
diff --git a/upgrade-nova b/upgrade-nova
--- a/upgrade-nova
+++ b/upgrade-nova
@@ -2,6 +2,24 @@
 
 # ``upgrade-nova``
 
+echo "*********************************************************************"
+echo "Begin $0"
+echo "*********************************************************************"
+
+# Clean up any resources that may be in use
+cleanup() {
+    set +o errexit
+
+    echo "*********************************************************************"
+    echo "ERROR: Abort $0"
+    echo "*********************************************************************"
+
+    # Kill ourselves to signal any calling process
+    trap 2; kill -2 $$
+}
+
+trap cleanup SIGHUP SIGINT SIGTERM
+
 # Keep track of the grenade directory
 GRENADE_DIR=$(cd $(dirname "$0") && pwd)
 
@@ -16,7 +34,12 @@ GetDistro
 # Source params
 source $GRENADE_DIR/grenaderc
 
-# For debugging
+# This script exits on an error so that errors don't compound and you see
+# only the first error that occured.
+set -o errexit
+
+# Print the commands being run so that we can see the command that triggers
+# an error.  It is also useful for following allowing as the install occurs.
 set -o xtrace
 
 
@@ -205,3 +228,8 @@ screen_it n-novnc "cd $NOVNC_DIR && ./utils/nova-novncproxy --config-file $NOVA_
 screen_it n-xvnc "cd $NOVA_DIR && $NOVA_BIN_DIR/nova-xvpvncproxy --config-file $NOVA_CONF"
 screen_it n-cauth "cd $NOVA_DIR && $NOVA_BIN_DIR/nova-consoleauth"
 is_service_enabled swift3 || screen_it n-obj "cd $NOVA_DIR && $NOVA_BIN_DIR/nova-objectstore"
+
+set +o xtrace
+echo "*********************************************************************"
+echo "SUCCESS: End $0"
+echo "*********************************************************************"
