Indicate to plugin resource verification where we are
This makes the resource verify commands take a second argument that
indicates if we are pre-upgrade or post-upgrade. This may be needed
in order to validate things that will not be true before, but must
be true after an upgrade.

Change-Id: I6383c5f641bb8eb7fee6f1fbd41bca3a281d9636

diff --git a/inc/plugin b/inc/plugin
--- a/inc/plugin
+++ b/inc/plugin
@@ -92,6 +92,7 @@ function shutdown_services {
 function resources {
     # which resource phase are we in
     local phase=$1
+    local side=$2
     local project=""
 
     # bail early if we aren't going to do this level of verification.
@@ -115,7 +116,7 @@ function resources {
         if [[ -e $resource ]]; then
             # NOTE(sdague): we might need to set topdir differently?
             TOP_DIR=$BASE_DEVSTACK_DIR LOGDIR=$LOGDIR \
-                   $resource $phase || die $LINENO "Failed to run ``$resource $phase``"
+                   $resource $phase $side || die $LINENO "Failed to run ``$resource $phase $side``"
         fi
     done
 }
