modularize shutdown
This breaks the content out of stop-base into a set of modular
shutdown.sh scripts so that every service can control it's own
shutdown. Services are shut down in reverse order under the theory
that will prevent services from calling services they depend on and
blocking their shutdown. Keystone had a habit of not going down if it
was first in the list.

We also need to manage TOP_DIR because many devstack scripts source
other devstack scripts by TOP_DIR. In the base case we make it
TARGET_DEVSTACK_DIR, however when we run shutdown we reference the
BASE_DEVSTACK_DIR instead.

This also moves all the stop-base service checks into the modular
shutdown scripts.

Depends-On: I9138a8370be06e6c9d2dacbec1b0ffd4928e603d

... as apparently stop_neutron does do anything useful in juno, and
the neutron project was relying on global pkills to make their
services actually shut down.

Change-Id: I02599b95bde61ade34220251e896f6d4c4122c22

diff --git a/inc/plugin b/inc/plugin
--- a/inc/plugin
+++ b/inc/plugin
@@ -22,4 +22,28 @@ function load_settings {
             source $settings
         fi
     done
+    export UPGRADE_PROJECTS
+}
+
+function shutdown_services {
+    echo "Upgrade projects: $UPGRADE_PROJECTS"
+    # iterate in reverse under the theory that we should take down
+    # services in opposite order
+    local reverse_projects=""
+    local project=""
+    for project in $UPGRADE_PROJECTS; do
+        reverse_projects="$project $reverse_projects"
+    done
+
+    for project in $reverse_projects; do
+        echo "Looking for $project"
+        local dir=${PLUGIN_DIR[$project]}
+        if [[ -z "$dir" ]]; then
+            die $LINENO "Couldn't find project '$project' in plugin list"
+        fi
+        local shutdown=$dir/shutdown.sh
+        if [[ -e $shutdown ]]; then
+            TOP_DIR=$BASE_DEVSTACK_DIR $shutdown || die "Failed to shutdown $project"
+        fi
+    done
 }
