fix die functions
die requires the second param be $LINENO, there were 2 calling points
where that was wrong.

Change-Id: I0484270d7140be8863dd0c9521e868b393f27dd7

diff --git a/inc/plugin b/inc/plugin
--- a/inc/plugin
+++ b/inc/plugin
@@ -55,7 +55,7 @@ function shutdown_services {
         fi
         local shutdown=$dir/shutdown.sh
         if [[ -e $shutdown ]]; then
-            TOP_DIR=$BASE_DEVSTACK_DIR $shutdown || die "Failed to shutdown $project"
+            TOP_DIR=$BASE_DEVSTACK_DIR $shutdown || die $LINENO "Failed to shutdown $project"
         fi
     done
 }
@@ -79,7 +79,7 @@ function resources {
         local resource=$dir/resources.sh
         if [[ -e $resource ]]; then
             # NOTE(sdague): we might need to set topdir differently?
-            TOP_DIR=$BASE_DEVSTACK_DIR $resource $phase || die "Failed to run ``$resource $phase``"
+            TOP_DIR=$BASE_DEVSTACK_DIR $resource $phase || die $LINENO "Failed to run ``$resource $phase``"
         fi
     done
 }
